spring:
  servlet:
    multipart:
      max-file-size: 20GB  # 单个文件最大大小
      max-request-size: 30GB  # 整个请求的最大大小
  application:
    name: secAI-container-engine
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SecAI_backend
    username: root
    password: root


knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: v1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.example.secaicontainerengine.controller

logging:
  level:
    root: info

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false  # 是否开启下划线和驼峰的映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 这个配置设置 MyBatis 的日志实现，指定为 StdOutImpl 表示将日志直接输出到标准输出（控制台）。
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.example.secaicontainerengine.pojo.entity

k8s:
  config: k8s/config
  yaml: template/Pod.yml
  adversarial-yaml: template/attack_pod.yml

sftp:
#  host: 10.195.76.134
  host: 10.195.9.104
  port: 22
  username: nfs
  password: 123456
  flag: data.done #创建一个该名字的空文件，代表数据上传nfs服务器完毕

nfs:
  # /home/nfs/k8s/model_data/userId/modelId/originData
  rootPath: /home/nfs/k8s
  origin-data: originData